{
 "title": "Monitoramento da Qualidade do Ar - Visualização por Localidade",
 "description": "Dashboard que apresenta de forma detalhada o monitoramento da qualidade do ar por localidade. Permite selecionar a estação de interesse e visualizar os dispositivos associados, acompanhando a evolução do Índice de Qualidade do Ar (IQAr) e dos principais poluentes atmosféricos (PM10, PM2.5, O3, NO2, SO2, CO). A visualização facilita a análise temporal, a comparação entre métricas e a identificação de condições críticas de exposição em cada região monitorada.",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "station",
    "label": "Localidade",
    "query": {}
   },
   {
    "name": "device",
    "label": "Dispositivo",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "$station | Qualidade do Ar",
   "type": "stat",
   "description": "Classificação do Índice de Qualidade do Ar (IQAr), calculado a partir dos principais poluentes, segundo metodologia do Ministério do Meio Ambiente.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "\\[${device}\\] - IQAr Máximo" },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "$station | Alarme(s) Ativo(s)",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "" },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": false,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "$station" },
     "trigger": { "filter": "/IQAr/" }
    }
   ]
  },
  {
   "title": "$station | Linha do Tempo do IQAr",
   "type": "state-timeline",
   "description": "Visualização em formato de linha do tempo (State timeline) que apresenta a evolução dos índices de qualidade do ar (IQAr) \ne dos principais poluentes monitorados pelo dispositivo selecionado. Cada linha representa uma métrica específica \n(IQAr Máximo, PM10, PM2.5, SO2, NO2, O3, CO), com valores codificados por cores conforme a escala de severidade. \nPermite identificar rapidamente padrões, variações e períodos críticos de exposição na localidade escolhida ($station).",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "\\[${device}\\] - IQAr Máximo" },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "\\[${device}\\] - IQAr - PM10" },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "\\[${device}\\] - IQAr - PM2.5" },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "\\[${device}\\] - IQAr - SO2" },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "\\[${device}\\] - IQAr - NO2" },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "\\[${device}\\] - IQAr - O3" },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "\\[${device}\\] - IQAr - CO" },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "$station | Monitoramento do IQAr",
   "type": "timeseries",
   "description": "Gráfico de série temporal que apresenta a evolução do Índice de Qualidade do Ar (IQAr) e dos poluentes associados \nao longo do tempo para a localidade selecionada ($station). Os dados permitem analisar tendências, identificar \npicos de concentração e acompanhar variações em relação aos limites de referência, com estatísticas de valor \nmínimo, médio e máximo exibidas na tabela de apoio.",
   "gridPos": { "h": 18, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "\\[${device}\\] - IQAr Máximo" },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "\\[${device}\\] - IQAr - PM10" },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "\\[${device}\\] - IQAr - PM2.5" },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "\\[${device}\\] - IQAr - SO2" },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "\\[${device}\\] - IQAr - NO2" },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "\\[${device}\\] - IQAr - O3" },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "\\[${device}\\] - IQAr - CO" },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "$station | Monitoramento de Temperatura e Umidade do Ar",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "\\[${device}\\] - Temperatura" },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "\\[${device}\\] - Umidade do Ar"
     },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "$station | Monitoramento de Pressão",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": { "filter": "\\[${device}\\] - Pressão" },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "$station | Monitoramento de PM10 (µg/m³)",
   "type": "timeseries",
   "description": "Gráfico de série temporal que apresenta a evolução da concentração do poluente monitorado ao longo do tempo \nna localidade selecionada ($station). São exibidas as medições em tempo real e suas médias móveis (1h e 24h), \npermitindo identificar variações de curto e longo prazo, além de picos de concentração. A tabela inferior \nresume estatísticas de mínimo, média, máximo e último valor registrado, auxiliando na análise da qualidade \ndo ar e na comparação com limites de referência.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "µg/m³" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "\\[${device}\\] - PM10 \\(µg/m³\\) - Tempo Real"
     },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "\\[${device}\\] - PM10 \\(µg/m³\\) - Média móvel 1h"
     },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "\\[${device}\\] - PM10 \\(µg/m³\\) - Média móvel 24h"
     },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "$station | Monitoramento de PM2.5 (µg/m³)",
   "type": "timeseries",
   "description": "Gráfico de série temporal que apresenta a evolução da concentração do poluente monitorado ao longo do tempo \nna localidade selecionada ($station). São exibidas as medições em tempo real e suas médias móveis (1h e 24h), \npermitindo identificar variações de curto e longo prazo, além de picos de concentração. A tabela inferior \nresume estatísticas de mínimo, média, máximo e último valor registrado, auxiliando na análise da qualidade \ndo ar e na comparação com limites de referência.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "µg/m³" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "\\[${device}\\] - PM2.5 \\(µg/m³\\) - Tempo Real"
     },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "\\[${device}\\] - PM2.5 \\(µg/m³\\) - Média móvel 1h"
     },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "\\[${device}\\] - PM2.5 \\(µg/m³\\) - Média móvel 24h"
     },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "$station | Monitoramento de SO2 (µg/m³)",
   "type": "timeseries",
   "description": "Gráfico de série temporal que apresenta a evolução da concentração do poluente monitorado ao longo do tempo \nna localidade selecionada ($station). São exibidas as medições em tempo real e suas médias móveis (1h e 24h), \npermitindo identificar variações de curto e longo prazo, além de picos de concentração. A tabela inferior \nresume estatísticas de mínimo, média, máximo e último valor registrado, auxiliando na análise da qualidade \ndo ar e na comparação com limites de referência.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "µg/m³" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "\\[${device}\\] - SO2 \\(µg/m³\\) - Tempo Real"
     },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "\\[${device}\\] - SO2 \\(µg/m³\\) - Média móvel 1h"
     },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "\\[${device}\\] - SO2 \\(µg/m³\\) - Média móvel 24h"
     },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "$station | Monitoramento de NO2 (µg/m³)",
   "type": "timeseries",
   "description": "Gráfico de série temporal que apresenta a evolução da concentração do poluente monitorado ao longo do tempo \nna localidade selecionada ($station). São exibidas as medições em tempo real e máxima de 1h, \npermitindo identificar variações de curto e longo prazo, além de picos de concentração. A tabela inferior \nresume estatísticas de mínimo, média, máximo e último valor registrado, auxiliando na análise da qualidade \ndo ar e na comparação com limites de referência.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "µg/m³" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "\\[${device}\\] - NO2 \\(µg/m³\\) - Tempo Real"
     },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "\\[${device}\\] - NO2 \\(µg/m³\\) - Máxima de 1h"
     },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "$station | Monitoramento de O3 (µg/m³)",
   "type": "timeseries",
   "description": "Gráfico de série temporal que apresenta a evolução da concentração do poluente monitorado ao longo do tempo \nna localidade selecionada ($station). São exibidas as medições em tempo real e suas médias móveis (1h e 8h), \npermitindo identificar variações de curto e longo prazo, além de picos de concentração. A tabela inferior \nresume estatísticas de mínimo, média, máximo e último valor registrado, auxiliando na análise da qualidade \ndo ar e na comparação com limites de referência.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "µg/m³" } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "\\[${device}\\] - O3 \\(µg/m³\\) - Tempo Real"
     },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "\\[${device}\\] - O3 \\(µg/m³\\) - Média móvel 1h"
     },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "\\[${device}\\] - O3 \\(µg/m³\\) - Máxima média móvel de 8h"
     },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "$station | Monitoramento de CO (ppm)",
   "type": "timeseries",
   "description": "Gráfico de série temporal que apresenta a evolução da concentração do poluente monitorado ao longo do tempo \nna localidade selecionada ($station). São exibidas as medições em tempo real e suas médias móveis (1h e 8h), \npermitindo identificar variações de curto e longo prazo, além de picos de concentração. A tabela inferior \nresume estatísticas de mínimo, média, máximo e último valor registrado, auxiliando na análise da qualidade \ndo ar e na comparação com limites de referência.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "\\[${device}\\] - CO \\(ppm\\) - Tempo Real"
     },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "\\[${device}\\] - CO \\(ppm\\) - Média móvel 1h"
     },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    },
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "iot-devices" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "\\[${device}\\] - CO \\(ppm\\) - Média móvel 8h"
     },
     "itemTag": { "filter": "$station" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  }
 ]
}