#cloud-config
#
# Instalação automatizada do Zabbix com PostgreSQL + TimescaleDB
# Ubuntu Server 22.04 LTS via Multipass
# Autor: Helton Medeiros
# Data: 20 de junho de 2025

hostname: zabbix
manage_etc_hosts: true
package_update: true
package_upgrade: true

# Rede via DHCP (IP fixo será configurado posteriormente)
network:
  version: 2
  ethernets:
    ens3:
      dhcp4: true

packages:
  - wget
  - gnupg
  - postgresql
  - postgresql-contrib
  - ufw

runcmd:
  # Repositório Zabbix
  - wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb
  - dpkg -i zabbix-release_6.0-4+ubuntu22.04_all.deb
  - apt update

  # Instalação Zabbix + TimescaleDB
  - apt install -y zabbix-server-pgsql zabbix-frontend-php zabbix-apache-conf zabbix-agent timescaledb-postgresql-15

  # Configuração do PostgreSQL
  - systemctl enable postgresql
  - systemctl start postgresql
  - sudo -u postgres psql -c "CREATE DATABASE zabbix;"
  - sudo -u postgres psql -c "CREATE USER zabbix WITH PASSWORD 'zabbix';"
  - sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE zabbix TO zabbix;"

  # Otimização TimescaleDB
  - timescaledb-tune --quiet --yes

  # Configurar senha no arquivo de config do Zabbix
  - sed -i 's/^# DBPassword=/DBPassword=zabbix/' /etc/zabbix/zabbix_server.conf

  # Importação do schema do Zabbix
  - zcat /usr/share/doc/zabbix-server-pgsql*/create.sql.gz | sudo -u zabbix psql -U zabbix -d zabbix

  # Iniciar e habilitar serviços
  - systemctl restart zabbix-server
  - systemctl enable zabbix-server
  - systemctl restart apache2
  - systemctl enable apache2
  - systemctl restart zabbix-agent
  - systemctl enable zabbix-agent

  # Configuração do firewall
  - ufw allow 22
  - ufw allow 80
  - ufw allow 10050
  - ufw allow 10051
  - ufw --force enable
